### ISSUE TITLE
内部DBが肥大化する&パフォーマンスが劣化する

### ISSUE THREAD

**Issue by nyankichi820** [cookpad/puree-ios#7]
こんにちは
pureeを使用しているプロジェクトで報告があったのですが、導入後アプリ起動のパフォーマンスがアプリを使っていくたびに劣化するとの報告がありました。

調べて頂いたら

・logデータ1万件、logDBサイズ10MB、log初期化時間1.5秒
・logデータ2万件、logDBサイズ20MB、log初期化時間3.0秒
※logDB : Library/Caches/com.cookpad.PureeData.default/logs.db
と肥大化しているようで、また起動時にイベントを投げるところがあり、そこで遅くなっている模様でした。

パフォーマンスの劣化の原因としては下記のPRにあるようにDBの書き込みをメインスレッドで行っており、DBのサイズの肥大化に伴い劣化しているのかなと思われます。
#6

こちら何かしら、回避策はありますでしょうか？

**Comment by nyankichi820** [comment]
logのpost時ではなくinitialize時点で時間がかかってしまう模様です。

 [[PURLogger alloc] initWithConfiguration:configuration];

**Comment by nyankichi820** [comment]
すみません、、単純にwritechunk後にcompletionを呼んでないだけの模様でした。。

**Comment by slightair** [comment]
解決されたようで良かったです。Puree を使っていただきありがとうございます :smile_cat: :sparkles:

**Comment by nyankichi820** [comment]
ちゃんと調べずに投げてしまい申し訳ありません...!

便利に使っております！
