### ISSUE TITLE
Update YapDatabase

### ISSUE THREAD

**Issue by slightair** [cookpad/puree-ios#8]
I tried to update YapDatabase 2.8.3, but some stress tests are failed. :cry:

**Comment by chuganzy** [comment]
直接の原因は https://github.com/cookpad/puree-ios/pull/6 でしょうか？
私の手元でYapDatabaseを2.8.3にしてテストを走らせましたがすべてパスしましたので
マシンスペック次第では通らない（もしくは通る）ことがあるのでしょうね…

**Comment by slightair** [comment]
ちょっとテストも変なので書きなおそうと思っています。

**Comment by slightair** [comment]
Ref: https://github.com/cookpad/puree-ios/pull/12
